### PR TITLE
Adds Going to Production Checklist

### PR DESCRIPTION
**Pull request by djejaquino**
## Description

-

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

- [x] Not Applicable

## Rollback / Rollforward Procedure

- [ ] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

### CODE REVIEW

**Comment by armsteadj1** [comment]
Looks like the border on the bottom is in the wrong location - i didn't check other pages to see if it it was happening else where to understand if this is an existing problem or just with this page layout

image

**Comment by armsteadj1** [comment]
did you mean for this to be here without an icon?

image

**Comment by djejaquino** [comment]
> Looks like the border on the bottom is in the wrong location - i didn't check other pages to see if it it was happening else where to understand if this is an existing problem or just with this page layout
> 
> image

Looks like this only happens in Vercel preview

**Comment by djejaquino** [comment]
> did you mean for this to be here without an icon?
> 
> image

Waiting for the design team to provide the icons

**Review by armsteadj1 — APPROVED** [review]

**Pull request merged**
